### ISSUE TITLE
Syntax Highlighting for Constructor Arguments on Multiple Lines

### ISSUE THREAD

**Issue by JKTKops** [atom-haskell/language-haskell#123]
Note: This is a minor issue.

It seems like Github is using the grammar in this repository to perform syntax highlighting on fenced code blocks containing Haskell code. In one of my projects, I have this (reduced for brevity) code block:

```Haskell
data PhExpr id
     = PhVar id
     | OpApp (LPhExpr id)
             (LPhExpr id)
             (LPhExpr id)
     | NegApp (LPhExpr id)
```

The second two arguments to the `OpApp` constructor are highlighted as new constructors, rather than as arguments to the `OpApp` constructor.

**Comment by lierdakil** [comment]
Hi. I've attempted to fix this in v1.19.0, and it seems to work in most common cases (that is, tests pass), but the fix is somewhat brittle due to deficiencies in the Atom's grammar model, so I might have to revert it down the line, if there is a particularly nasty corner case lurking somewhere.

Please report any highlighting problems you might encounter with the new release.
