### ISSUE TITLE
This package appears unmaintained

### ISSUE THREAD

**Issue by benogle** [atom-haskell/language-haskell#29]
A maintained fork is present at  https://github.com/atom-haskell/language-haskell. We plan to point the Atom [package listing entry](https://atom.io/packages/language-haskell) to this maintained fork on __June 1st__ provided no interaction on this thread. Other options: 

* Fix deprecations on this fork
* Transfer ownership of the repo to @lierdakil

Thanks!

**Comment by lierdakil** [comment]
Any update on this? June, 1st came and gone, but it doesn't seem like I'm able to publish new version yet.

**Comment by benogle** [comment]
Sorry, I've been working on the settings view to deal with deprecated packages. We will release this week with the deprecations removed, and I will move this before then.

**Comment by lierdakil** [comment]
Ok, great.

**Comment by benogle** [comment]
@jroesch can you transfer this repo to @lierdakil. He can add the repo to the https://github.com/atom-haskell org.

**Comment by lierdakil** [comment]
Actually, I've invited @jroesch to atom-haskell back when I tried to reach him on the subject of transferring ownership. I have since forked this repo to atom-haskell though, so I'm not sure how  github would react to anyone trying to transfer this repo there.
But in theory, @jroesch, you could transfer directly to atom-haskell, if you choose to. I'm available via e-mail if there are questions/complications (see github profile, if you missed my e-mail back when I tried to reach you)

**Comment by lierdakil** [comment]
So... I'm starting to get a little bit concerned. If `language-haskell` is not updated soon, half of Haskell support for Atom won't work on next update. I can work around that, by introducing a new package, but that would be a relatively painful thing to do for all parties involved.

**Comment by benogle** [comment]
It will still work. It doesn't have critical deprecations. But yes,
transferring it would be ideal

**Comment by lierdakil** [comment]
Ok, repository transferred, deprecations fixed. Closing this now.
