### ISSUE TITLE
Comments inside module declarations are not highlighted as comments

### ISSUE THREAD

**Issue by jplatte** [atom-haskell/language-haskell#32]
This applies to both single-line and multiline comments.

**Comment by lierdakil** [comment]
I could use an example, if that's possible. Thanks.

**Comment by lierdakil** [comment]
Scratch that. I think I can release what I've been working on for the last couple weeks, and that should have comments fixed. If it doesn't work in 1.1.0, let me know.

**Comment by jplatte** [comment]
I didn't get a chance to test it on 1.1.0, as I already got an update for 1.1.1! Works fine though, thanks ;)

**Comment by joaomilho** [comment]
I'm using 1.12, and although it works if the comment is the beginning of the line, it doesn't if it's not
<img width="832" alt="screen shot 2017-02-04 at 20 19 14" src="https://cloud.githubusercontent.com/assets/308196/22620567/3f81faae-eb17-11e6-9a1e-6f53f3947f22.png">

**Comment by lierdakil** [comment]
Aw, crud. This works:
![image](https://cloud.githubusercontent.com/assets/7275622/22624631/9963cfcc-eb92-11e6-819b-a029efac684e.png)
That's what the issue was about. I've fixed it and then completely forgot that comments can appear outside of `()`.

So this should be fixed in v1.12.1. Thanks for reporting.

**Comment by joaomilho** [comment]
👍
