### ISSUE TITLE
Additional fileTypes for the Haskell grammar

### ISSUE THREAD

**Issue by jplatte** [atom-haskell/language-haskell#33]
I would love to have syntax highlighting for `.hsc` and `.chs` files, maybe they could just be added to the haskell grammar? I'm a bit unsure since those file types add some stuff that makes hlint error on trying to parse it, and setting the grammar to Haskell automatically enables hlint if you have the plugin installed. On the other hand the few syntactic additions don't really need new highlighting IMO.

Can grammars in Atom depend on one another? Maybe then creating new grammars wouldn't be a problem. Anyway, just FYI, `.hsc` belong to to https://github.com/ghc/hsc2hs, `.chs` files belong to `https://github.com/haskell/c2hs`. Thanks for reading!

**Comment by lierdakil** [comment]
It's possible to create new grammar that would include existing one. See https://github.com/atom-haskell/language-haskell/blob/master/grammars/literate%20haskell.cson for an example. hsc2hs should be simple enough, since as far as I remember, it uses `#pragma` syntax for extensions. c2hs is a bit harder to implement properly, since it uses `{#context ... #}` extensions, which make no sense in regular Haskell.

If you're somewhat good with regular expressions, adding a grammar is actually pretty easy. Getting it right is hard though. It may take some time for me to get to this, but you're free to create a pull request if you're impatient ;)

**Comment by jplatte** [comment]
I'm not impatient, but maybe I'll start working on it in the next weeks if nobody else does.

**Comment by lierdakil** [comment]
Finally got around to implementing at least something resembling this request. Feel free to open new issues if something goes awry or feels insufficient.

**Comment by jplatte** [comment]
Awesome, thanks! :)
