### ISSUE TITLE
Record decls are still broken

### ISSUE THREAD

**Issue by ulidtko** [atom-haskell/language-haskell#50]
While my PR #26 has been disregarded, record declarations are still **not** being highlighted correctly as of `v1.4.3` (current `master`):

![screenshot](http://i.imgur.com/DipuluE.png)

Going back to my fork, I see this after Atom reload:

![screenshot](http://i.imgur.com/3TcUMKf.png)

Clearly, record syntax support is broken in current master.

**Comment by lierdakil** [comment]
Thanks for reporting.

No offence, but your PR was closed because it really was already implemented independently, and there was no reason to switch. This particular bug is probably here since 1.3.0, due to GADT regex not being specific enough.

Long story short, I think this is fixed with 1.4.4. Please confirm, if possible.
