### ISSUE TITLE
Some keywords not highlighted

### ISSUE THREAD

**Issue by fatho** [atom-haskell/language-haskell#54]
As you can see in the following screenshot, the keywords `data`, `newtype`, etc. are not highlighted if they are followed by more text.

![atomhaskellhighlighting](https://cloud.githubusercontent.com/assets/3857449/10275623/21213e52-6b49-11e5-9609-5b085f2ebed9.png)

I'm using version 1.4.9 of language-haskell and version 1.0.19 of atom.

**Comment by lierdakil** [comment]
language-haskell treats some keywords differently depending on context. If you have standalone `data`, it will be interpreted as `keyword.other.haskell`, since we have no idea what it means, but it *is* a reserved keyword.

If you have it inside an expression that language-haskell was able to parse, it will be interpreted as `storage.type.data.haskell`, since, well, it's basically a storage type specifier.

With all that said, your syntax highlighting theme doesn't seem to recognize `storage.type` entities. Consider raising an issue with them.
