### ISSUE TITLE
The type announcement syntax highlighting has a bug

### ISSUE THREAD

**Issue by li-zhirui** [atom-haskell/language-haskell#67]
The type announcement after `where` will fail to be highlighted. For example, the `add'` function which follows after `where` won't be highlighted. 
```Haskell
add :: Int -> Int -> Int
add = add'
  where add' :: Int -> Int -> Int
        add' a b = a + b
```
But if I write code like the following, it can be hightlighted correctly.
```Haskell
add :: Int -> Int -> Int
add = add'
  where
        add' :: Int -> Int -> Int
        add' a b = a + b
```
Both code are compiled, but the previous one can't be highlighted correctly.

oops, I found that the syntax highlighting of github markdown is not correct either.

PS. Hope my poor English can be understood. :)

**Comment by lierdakil** [comment]
Yes, that is expected. Long story short, this is a limitation of Atom's syntax model which forbids backtracking.

Consider this snippet:

```haskell
{-# LANGUAGE ScopedTypeVariables #-}

main :: IO ()
main = putStrLn test
  where test :: String
          = "asd"
```

At the time of parsing `test :: String` there is no way to decide if it's a declaration or definition. So some compromises had to be made. In this case, parser assumes that if it's on a line by itself, it's declaration. Otherwise, it's definition.

Only way to truly fix this is implementing a true backtracking parser. Which is not possible at the moment (if curious, search https://github.com/atom/atom/issues for 'grammar' -- general resolution is "maybe in the future")

**Comment by li-zhirui** [comment]
Oh, I see. Thanks for your reply.
