### ISSUE TITLE
Auto generation

### ISSUE THREAD

**Issue by AnthonyJacob** [atom-haskell/language-haskell#78]
(1)
```
case expression of
    pattern -> expression
    otherwise -> expression
```
uses -> instead of →
(2)
\+tab = ${1:pattern} -> expression
\ is missing and  ${1:pattern} must be selected manually to be rewritten
(3)
Would you mind adding unicode lambda?
`λ p -> p` instead of `\ p -> p`

Do you know any font, in which unicode chars like `→ ⤜ ←  ∷ ↢` etc. look better then` -> >>- <- :: -<`?

**Comment by lierdakil** [comment]
Okay, (2) fixed. I'm not too keen on (1) and (3), since using unicode characters requires `UnicodeSyntax` GHC extension. So defaulting to those doesn't seem like a particularly good idea. You could probably override those yourself if you want to, since those are just predefined snippets. Add your snippets for `.source.haskell` scope and you should be good.

As for font, I'm using FiraCode, which has ligatures for most special operators. Those mostly look better than unicode equivalents. I'm not aware of any *monospace* fonts that have nice-looking unicode characters compared to ligatures.
