### ISSUE TITLE
undefined Grammar's in the package settings

### ISSUE THREAD

**Issue by duimpera** [atom-haskell/language-haskell#92]
In the settings page of the language-haskell package, there are 3 'undefined Grammar' grammars. Their scopes are:
- hint.haskell
- hint.message.haskell
- hint.message.haskell

Probably caused by 98159fb.

**Comment by lierdakil** [comment]
That is by design. Those grammars are not intended to be selectable with
grammar selector and are instead used internally by ide-haskell packages. I
will see if I can hide those from settings page when I have some time.

2 окт. 2016 г. 11:27 ПП пользователь "duimpera" <notifications@github.com>
написал:

**Comment by lierdakil** [comment]
Relevant pull requests:

https://github.com/atom/grammar-selector/pull/34
https://github.com/atom/settings-view/pull/872
