### ISSUE TITLE
Dollar sign and backtick break highlight in Literate Haskell

### ISSUE THREAD

**Issue by yudai-nkt** [atom-haskell/language-haskell#93]
Migrated from area/language-latex#93.

I have no experience of writing Haskell, but `$` and `` ` `` in the following code breaks the syntax highlight according to @estebanlan.

```lhs
This is how this looks until I do this $

> f :: Int -> Int -> FieldElem
> f k 2 = FE2 $ F2 k

Same with `

> doesn't matter if I close it ` See?
```

__w/ `language-latex` enabled:__
![enabled](https://cloud.githubusercontent.com/assets/13291527/19478880/31ba0076-957f-11e6-9d1a-2e7e323a1f3e.png)

__w/ `language-latex` disabled:__
![disabled](https://cloud.githubusercontent.com/assets/13291527/19478895/3f952be4-957f-11e6-9019-d37b4fefc978.png)

It is true that some grammar scopes in `text.tex.latex` affects the behaviour, but `language-haskell` seems to have some LaTeX-related codes. That's why I opened this issue.

Sorry if our package is to blame. In such case, I will highly appreciate it if you would teach me the meaning of each line in the code above. I'm not familiar with Literate Haskell, so I don't know what to fix.

**Comment by lierdakil** [comment]
Literate Haskell grammar assumes lhs2TeX syntax, so anything that's not code is considered LaTeX, which is used as an included grammar. So that is why there is some interaction between language-latex and language-haskell.

Now then, using naked `$` in LaTeX code is an error, since `$` usually delimit math. So first line is not valid LaTeX and won't work properly with lhs2TeX+pdflatex (or similar). I would argue that highlighting doesn't *have* to work on invalid input.

However, I should point out that paragraph breaks are not allowed in LaTeX math, so maybe you could highlight paragraph break as invalid and assume that scope is closed. F.ex., this is invalid LaTeX:

```latex
$
\int_0^\infty \frac{1}{x^2+1} \mathrm{d}x = \frac{\pi}{2}

$
```

Now we're left with backticks. Backticks signify curly opening quotes in LaTeX, but those are just shorthands for typographic symbols, and do not *really* define an environment. So I would argue that

```latex
`...'
```

shouldn't be highlighted as such.

```latex
`, ``, ', ''
```
are special, but anything inside those isn't.

**Comment by yudai-nkt** [comment]
> So first line is not valid LaTeX and won't work properly with lhs2TeX+pdflatex (or similar).

Good to hear that and I agree to your opinion.

Regarding the blank line in math mode, this issue is something I sometimes consider fixing but haven't yet. I will work on it when I have time.

Quoting highlight is very problematic and we have several issues about it especially when the string spans multiple line. That being said, abolishing quoting highlight sounds a bit too brave. Discussion should be made in our issue tracker.

Anyway, thanks for explaining about lhs2TeX! It clarified the responsibility for this problem.
